### ISSUE TITLE
Login not working for me

### ISSUE THREAD

**Issue by Stefan4691** [p0l0/hagruenbeck_cloud#12]
### System Health details

Just installed the integration.
After restart, I wanted to activate it.

I've entered the username and password and get 'Unexpected error'

On my phone app, the device is listed and shows values.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/p0l0/hagruenbeck_cloud/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I get this in the log file:
Traceback (most recent call last):
File "/config/custom_components/gruenbeck_cloud/config_flow.py", line 48, in async_step_user
self.devices = await self.get_devices(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/gruenbeck_cloud/config_flow.py", line 131, in get_devices
devices = await api.get_devices()
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pygruenbeck_cloud/pygruenbeck_cloud.py", line 423, in get_devices
devices.append(Device.from_json(device))
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pygruenbeck_cloud/models.py", line 275, in from_json
return Device(**new_data)
^^^^^^^^^^^^^^^^^^
TypeError: Device.__init__() got an unexpected keyword argument 'access_point_name'

### Reproduction steps

1. click 'add imtegration'
2. enter user and password
3. submit

It returns the error

If I intentionally use a wrong user/password, I'm just getting
2024-01-21 04:14:03.790 ERROR (MainThread) [pygruenbeck_cloud.pygruenbeck_cloud] Unable to login

So, I guess user/password are correct in the above case.

### Debug logs

```text
I get this in the log file:
Traceback (most recent call last):
File "/config/custom_components/gruenbeck_cloud/config_flow.py", line 48, in async_step_user
self.devices = await self.get_devices(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/gruenbeck_cloud/config_flow.py", line 131, in get_devices
devices = await api.get_devices()
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pygruenbeck_cloud/pygruenbeck_cloud.py", line 423, in get_devices
devices.append(Device.from_json(device))
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pygruenbeck_cloud/models.py", line 275, in from_json
return Device(**new_data)
^^^^^^^^^^^^^^^^^^
TypeError: Device.__init__() got an unexpected keyword argument 'access_point_name'
```

**Comment by p0l0** [comment]
Which model do you have?

Your response seems to have additional elements, which I'm not getting.

Can you please activate debug logging for the integration and try it again, you should see in the logs the response from Grünbeck Cloud, it should be look like this, before the exception:

```
Response from URL https://prod-eu-gruenbeck-api.azurewebsites.net/api/devices?api-version=2020-08-03 with status 200 was [{'type': 18, 'hasError': False, 'id': 'softliQ.D/BS20445420', 'series': 'softliQ.D', 'serialNumber': 'BS20445420', 'name': 'softIQ:SD18', 'register': True}]
```

For activate debug logging, you need to modify the logger in your configuartion.yaml to something like this:

```
logger:
  default: info
  logs:
    custom_components.gruenbeck_cloud: debug
```

With that I can analyze which fields are missing, in your error I only see, that _access_point_name_ is missing, but maybe there are more.

**Comment by nielssch** [comment]
I have an SC18 and got exactly the same error messages as @Stefan4691 

@p0l0 I did add the lines to my configuration.yaml and restarted HA. I am still not getting additional details in the log file. Since the integration never gets added due to the failed login, I cannot activate debug logging using the UI.

Wish I could help more, since I would love the integrate my SC18 in HA without having to use ioBroker.

Tanks a lot in advance for looking into it!

**Comment by p0l0** [comment]
To see the Debug log entries, you need to click on the `Load Full Logs` button under `Settings`->`System`->`Logs`, you will see entries for the integration, also if the integration never gets added.

Nevertheless  with the new version 0.1.0 I changed the way how responses are parsed, so that entries in json which are missing in the Python Class should be ignored. Please give it a try.

I also implemented in version 0.1.0 the [diagnostic](https://www.home-assistant.io/integrations/diagnostics/) dump option, so that after adding the integration, you can send me this diagnostic dump, so that i can check which properties your system is providing, which mine doesn't have.

**Comment by nielssch** [comment]
Thanks for your response and the new release. I installed 0.1.1 some minutes ago and tried to add the integration after restarting HA. The login still does not work, hence the integration is not getting added. The HA core log is showing these gruenbeck related lines:

2024-02-04 18:17:41.675 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration gruenbeck_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-02-04 18:22:13.536 WARNING (MainThread) [custom_components.gruenbeck_cloud.config_flow] 'has_error'
2024-02-04 18:22:35.775 WARNING (MainThread) [custom_components.gruenbeck_cloud.config_flow] 'has_error'

These are the only details I am getting:

Logger: custom_components.gruenbeck_cloud.config_flow
Source: custom_components/gruenbeck_cloud/config_flow.py:141
Integration: Grünbeck Cloud (documentation, issues)
First occurred: 18:22:13 (2 occurrences)
Last logged: 18:22:35
'has_error'

I hope this helps...

**Comment by p0l0** [comment]
Are you sure, that your SC18 is using cloud for data transmission? I just looked at the ioBroker implementation and for SC Models, they are using local API. 
Cloud implementation at ioBroker is only for SD Models.

If SC is also using Cloud, it seems to work differently to SD Models, that's probably the reason why login is not working.

**Comment by nielssch** [comment]
Well, good point. I am actually not sure. When using the Grünbeck App and logging in there, authentication is done using the URL https://gruenbeckb2c.b2clogin.com/ 
Therefore I was under the impression, that I am accessing the Grünbeck cloud. What is the URL your integration is using to authenticate?

**Comment by p0l0** [comment]
It's the same, but I think the following API requests which are done after login, are different for SC.

Do you have the possibility to run a python script? I could send you a script which uses directly the library and with verbose output, so that we can try to find out, what is being retuned, and how it maybe could be handled.

**Comment by nielssch** [comment]
Sure, I can run the script either on my Mac or the server currently running a python script doing rest calls to read the data and pushing them to telegraf.

**Comment by Cavekeeper** [comment]
I installed the app via HACS and when setting up I get the error message: Connection failed. In the LOG I find the entry:

`Logger: custom_components.gruenbeck_cloud.config_flow
Source: custom_components/gruenbeck_cloud/config_flow.py:141
Integration: Grünbeck Cloud (documentation, issues)
First occurred: 12:55:01 (1 occurrences)
Last logged: 12:55:01

'has_error'`

**Comment by ChaotenKurt** [comment]
I get the same error. 

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht  Logger: custom_components.gruenbeck_cloud.config_flow Quelle: custom_components/gruenbeck_cloud/config_flow.py:141 Integration: Grünbeck Cloud (Dokumentation, Probleme) Zum ersten Mal aufgetreten: 06:58:16 (2 Vorkommen) Zuletzt angemeldet: 07:08:33  'has_error'

**Comment by p0l0** [comment]
> Sure, I can run the script either on my Mac or the server currently running a python script doing rest calls to read the data and pushing them to telegraf.

Sorry, I was a little bit busy the last weeks. Please run this script, replacing <EMAIL> und <PASSWORD> with your login data.

To run the script, you need to install the `pygruenbeck_cloud` library. This can be done with pip, just run `pip install pygruenbeck_cloud`.

The script will show you every request and response from server, that will make it easier to find out, what is being returned, and try to find out what is different to SD Models.

```python
import asyncio
import logging

from pygruenbeck_cloud import PyGruenbeckCloud

logging.basicConfig(
    level=logging.DEBUG,
    format="[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s",
    datefmt="%d/%b/%Y %H:%M:%S",
)
_LOGGER = logging.getLogger(__name__)


class TestGruenbeck:
    async def init(self):
        """Demo function for testing."""
        try:
            async with PyGruenbeckCloud(
                username="<EMAIL>",
                password="<PASSWORD>",
            ) as gruenbeck:
                gruenbeck.logger = _LOGGER

                devices = await gruenbeck.get_devices()
                if len(devices) <= 0:
                    _LOGGER.warning("No devices!")
                    return
        except Exception as ex:
            _LOGGER.error(ex)


asyncio.run(TestGruenbeck().init())
```

**Comment by p0l0** [comment]
@Cavekeeper  and @ChaotenKurt which model do you have? It seems, as the hasError property is not being returned from the API.

**Comment by ChaotenKurt** [comment]
No problem at all, I have the following device: softliq:SC18 / software version V01.01.02

**Comment by Cavekeeper** [comment]
My device: softliq:SC18 / V01.00.27

**Comment by TheOnkelTank** [comment]
Hi, i have the same issue.
I had the integration running since Februar, but since Sunday my softliQ:SD18 does not initialize any more.
Now I removed the device and tried to reinitalize the complete device, but now the connection always failed.
And it seams https://gruenbeckb2c.b2clogin.com/ does not work anymore.

But I can access the SD18 via the app without problems

**Comment by TheOnkelTank** [comment]
> Hi, i have the same issue. I had the integration running since Februar, but since Sunday my softliQ:SD18 does not initialize any more. Now I removed the device and tried to reinitalize the complete device, but now the connection always failed. And it seams https://gruenbeckb2c.b2clogin.com/ does not work anymore.
> 
> But I can access the SD18 via the app without problems

It's working again. It was a problem with HA and HACS. I had to reinstall HA and load a Backup. Now it is working again.

**Comment by ChaotenKurt** [comment]
I have now installed a completely new Home Assistant. Without a backup. I then installed HACS and then the adapter. Unfortunately without success, again I get the same error message that the login did not work.

**Comment by ck301** [comment]
Hi! kann mir jemand sagen wie ich das für meine Grünbeck SC zum laufen bekomme? login geht nicht.
Hi! can anybody explain me how i get this running for my Grünbeck SC? login is not possible.

Thank you

**Comment by p0l0** [comment]
After checking the ioBroker adapter and what the App does, the SC model has a complete different way of working and therefore also a complete different implementation.

Unfortunately I don't have an SC model and currently I also don't have the time for doing a complete new implementation :(

The SC model is threaten in the ioBroker adapter and in the App as "local/standalone", probably it should be a complete different library instead of being implemented into the (pygruenbeck_cloud)[https://github.com/p0l0/pygruenbeck_cloud] library, but maybe using the same HA component is possible.

**Comment by tempo3** [comment]
Hi, login not working. Device SC18, 
home-assistant.log: WARNING (MainThread) [custom_components.gruenbeck_cloud.config_flow] 'has_error'
The Android-app is running and values are available.
Thx a lot in advance for any kind of support to get this integration running.

**Comment by p0l0** [comment]
For the SC Models, you need to use the local API, for that I have seen that tizianodeg created the integration [gruenbeck_softliQ_SC](https://github.com/tizianodeg/gruenbeck_softliQ_SC).

I will close this Issue, as my integration is only for Cloud only models.
